version: '3'

services:
  rsyslog:
    image: SZÜKSÉGES DOCKER IMAGE
    container_name: rsyslog-server

    ports:
      - "514:514/udp"
      - "514:514/tcp"

    volumes:
      - LOGS MAPPA CSATOLÁSA
      - ./config/rsyslog.conf:/etc/rsyslog.conf

    restart: unless-stopped
